"""Walk lifecycle and events (PRD §9–11).

IDs are generated by the client so writes queued offline can be retried safely:
creating a walk or event that already exists returns the existing row, and
start/finish on a walk that's already past that step are no-ops (PRD §26).
"""

import uuid
from datetime import UTC, datetime, timedelta
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.db import get_db
from app.deps import current_user, get_owned
from app.models import EVENT_TYPES, Dog, User, Walk, WalkEvent

router = APIRouter(prefix="/api/walks", tags=["walks"])

EventType = Literal[EVENT_TYPES]  # type: ignore[valid-type]
GpsMode = Literal["live", "upload"]
WalkStatus = Literal["created", "active", "completed", "published"]
# Client clocks drift; reject only timestamps clearly in the future.
MAX_CLOCK_SKEW = timedelta(minutes=10)


class DogSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str


class EventOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    type: str
    timestamp: datetime
    notes: str | None
    latitude: float | None
    longitude: float | None


class WalkOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    dog: DogSummary
    status: str
    track_gps: bool
    track_stats: bool
    track_photos: bool
    track_activity: bool
    gps_mode: str | None
    started_at: datetime | None
    ended_at: datetime | None
    distance_meters: float | None
    pre_walk_notes: str | None
    notes: str | None
    created_at: datetime


class WalkDetailOut(WalkOut):
    events: list[EventOut]


class WalkListItem(WalkOut):
    event_count: int


class WalkIn(BaseModel):
    id: uuid.UUID
    dog_id: int
    track_gps: bool = True
    track_stats: bool = True
    track_photos: bool = True
    track_activity: bool = True
    gps_mode: GpsMode | None = None
    pre_walk_notes: str | None = Field(default=None, max_length=5000)


class WalkPatch(BaseModel):
    pre_walk_notes: str | None = Field(default=None, max_length=5000)
    notes: str | None = Field(default=None, max_length=10000)


class StartIn(BaseModel):
    started_at: AwareDatetime


class FinishIn(BaseModel):
    ended_at: AwareDatetime


class EventIn(BaseModel):
    id: uuid.UUID
    type: EventType
    timestamp: AwareDatetime
    notes: str | None = Field(default=None, max_length=2000)
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)


class EventPatch(BaseModel):
    type: EventType | None = None
    timestamp: AwareDatetime | None = None
    notes: str | None = Field(default=None, max_length=2000)


def _clean(value: str | None) -> str | None:
    value = value.strip() if value else None
    return value or None


def _not_future(ts: datetime) -> datetime:
    if ts > datetime.now(UTC) + MAX_CLOCK_SKEW:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Time is in the future")
    return ts


def _editable(walk: Walk) -> Walk:
    if walk.status == "published":
        raise HTTPException(status.HTTP_409_CONFLICT, "Published walks can't be changed")
    return walk


@router.get("", response_model=list[WalkListItem])
def list_walks(
    status_: list[WalkStatus] | None = Query(default=None, alias="status"),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> list[WalkListItem]:
    counts = (
        select(WalkEvent.walk_id, func.count().label("n")).group_by(WalkEvent.walk_id).subquery()
    )
    q = (
        select(Walk, func.coalesce(counts.c.n, 0))
        .outerjoin(counts, counts.c.walk_id == Walk.id)
        .where(Walk.user_id == user.id)
        .order_by(Walk.started_at.desc().nulls_first(), Walk.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    if status_:
        q = q.where(Walk.status.in_(status_))
    return [
        WalkListItem.model_validate({**WalkOut.model_validate(w).model_dump(), "event_count": n})
        for w, n in db.execute(q)
    ]


@router.post("", response_model=WalkDetailOut, status_code=status.HTTP_201_CREATED)
def create_walk(
    body: WalkIn,
    response: Response,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> Walk:
    existing = db.get(Walk, body.id)
    if existing is not None:
        if existing.user_id != user.id:
            raise HTTPException(status.HTTP_409_CONFLICT, "Walk ID already in use")
        response.status_code = status.HTTP_200_OK
        return existing
    get_owned(db, Dog, body.dog_id, user)
    walk = Walk(
        id=body.id,
        user_id=user.id,
        dog_id=body.dog_id,
        status="created",
        track_gps=body.track_gps,
        track_stats=body.track_stats,
        track_photos=body.track_photos,
        track_activity=body.track_activity,
        gps_mode=(body.gps_mode or "live") if body.track_gps else None,
        pre_walk_notes=_clean(body.pre_walk_notes),
    )
    db.add(walk)
    db.commit()
    return walk


@router.get("/{walk_id}", response_model=WalkDetailOut)
def get_walk(
    walk_id: uuid.UUID, user: User = Depends(current_user), db: Session = Depends(get_db)
) -> Walk:
    return get_owned(db, Walk, walk_id, user)


@router.patch("/{walk_id}", response_model=WalkDetailOut)
def update_walk(
    walk_id: uuid.UUID,
    body: WalkPatch,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> Walk:
    walk = _editable(get_owned(db, Walk, walk_id, user))
    for field, value in body.model_dump(exclude_unset=True).items():
        setattr(walk, field, _clean(value))
    db.commit()
    return walk


@router.delete("/{walk_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_walk(
    walk_id: uuid.UUID, user: User = Depends(current_user), db: Session = Depends(get_db)
) -> None:
    walk = db.get(Walk, walk_id)
    if walk is None:
        return  # Already gone: a retried delete succeeds.
    walk = _editable(get_owned(db, Walk, walk_id, user))
    db.delete(walk)
    db.commit()


@router.post("/{walk_id}/start", response_model=WalkDetailOut)
def start_walk(
    walk_id: uuid.UUID,
    body: StartIn,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> Walk:
    walk = get_owned(db, Walk, walk_id, user)
    if walk.status == "created":
        walk.started_at = _not_future(body.started_at)
        walk.status = "active"
        db.commit()
    return walk


@router.post("/{walk_id}/finish", response_model=WalkDetailOut)
def finish_walk(
    walk_id: uuid.UUID,
    body: FinishIn,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> Walk:
    walk = get_owned(db, Walk, walk_id, user)
    if walk.status == "created":
        raise HTTPException(status.HTTP_409_CONFLICT, "Walk hasn't started")
    if walk.status == "active":
        ended_at = _not_future(body.ended_at)
        if walk.started_at and ended_at < walk.started_at:
            raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Walk ends before it starts")
        walk.ended_at = ended_at
        walk.status = "completed"
        # Distance comes from GPS points (Phase 5); duration is derived from the timestamps.
        db.commit()
    return walk


@router.post("/{walk_id}/events", response_model=EventOut, status_code=status.HTTP_201_CREATED)
def create_event(
    walk_id: uuid.UUID,
    body: EventIn,
    response: Response,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> WalkEvent:
    walk = get_owned(db, Walk, walk_id, user)
    existing = db.get(WalkEvent, body.id)
    if existing is not None:
        if existing.walk_id != walk.id:
            raise HTTPException(status.HTTP_409_CONFLICT, "Event ID already in use")
        response.status_code = status.HTTP_200_OK
        return existing
    _editable(walk)
    event = WalkEvent(
        id=body.id,
        walk_id=walk.id,
        type=body.type,
        timestamp=_not_future(body.timestamp),
        notes=_clean(body.notes),
        latitude=body.latitude,
        longitude=body.longitude,
    )
    db.add(event)
    db.commit()
    return event


def _owned_event(db: Session, walk: Walk, event_id: uuid.UUID) -> WalkEvent | None:
    event = db.get(WalkEvent, event_id)
    return event if event is not None and event.walk_id == walk.id else None


@router.patch("/{walk_id}/events/{event_id}", response_model=EventOut)
def update_event(
    walk_id: uuid.UUID,
    event_id: uuid.UUID,
    body: EventPatch,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> WalkEvent:
    walk = _editable(get_owned(db, Walk, walk_id, user))
    event = _owned_event(db, walk, event_id)
    if event is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Not found")
    fields = body.model_dump(exclude_unset=True)
    if fields.get("type"):
        event.type = fields["type"]
    if fields.get("timestamp"):
        event.timestamp = _not_future(fields["timestamp"])
    if "notes" in fields:
        event.notes = _clean(fields["notes"])
    db.commit()
    return event


@router.delete("/{walk_id}/events/{event_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_event(
    walk_id: uuid.UUID,
    event_id: uuid.UUID,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
) -> None:
    walk = _editable(get_owned(db, Walk, walk_id, user))
    event = _owned_event(db, walk, event_id)
    if event is not None:  # Already gone: a retried delete succeeds.
        db.delete(event)
        db.commit()
