"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 19:24:25.564074
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("service_area", sa.String(length=200), nullable=True),
        sa.Column("profile_photo", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "dogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_name", sa.String(length=100), nullable=True),
        sa.Column("photo", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dogs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dogs")),
    )
    op.create_index(op.f("ix_dogs_user_id"), "dogs", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "testimonials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_testimonials_rating")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_testimonials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_testimonials")),
    )
    op.create_index(op.f("ix_testimonials_user_id"), "testimonials", ["user_id"], unique=False)
    op.create_table(
        "walks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="created", nullable=False),
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
        sa.Column("track_gps", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("track_stats", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("track_photos", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("track_activity", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("pre_walk_notes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('created', 'active', 'completed', 'published')",
            name=op.f("ck_walks_status"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'unlisted', 'public')", name=op.f("ck_walks_visibility")
        ),
        sa.ForeignKeyConstraint(
            ["dog_id"], ["dogs.id"], name=op.f("fk_walks_dog_id_dogs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_walks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_walks")),
        sa.UniqueConstraint("share_token", name=op.f("uq_walks_share_token")),
    )
    op.create_index(op.f("ix_walks_dog_id"), "walks", ["dog_id"], unique=False)
    op.create_index("ix_walks_user_id_started_at", "walks", ["user_id", "started_at"], unique=False)
    op.create_table(
        "gps_points",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("walk_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("accepted", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["walk_id"], ["walks.id"], name=op.f("fk_gps_points_walk_id_walks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gps_points")),
    )
    op.create_index(
        "ix_gps_points_walk_id_timestamp", "gps_points", ["walk_id", "timestamp"], unique=False
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("walk_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_path", sa.String(length=255), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["walk_id"], ["walks.id"], name=op.f("fk_photos_walk_id_walks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
    )
    op.create_index(op.f("ix_photos_walk_id"), "photos", ["walk_id"], unique=False)
    op.create_table(
        "walk_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("walk_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "type IN ('pee', 'poop', 'water', 'fed', 'note', 'other')",
            name=op.f("ck_walk_events_type"),
        ),
        sa.ForeignKeyConstraint(
            ["walk_id"], ["walks.id"], name=op.f("fk_walk_events_walk_id_walks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_walk_events")),
    )
    op.create_index(
        "ix_walk_events_walk_id_timestamp", "walk_events", ["walk_id", "timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_walk_events_walk_id_timestamp", table_name="walk_events")
    op.drop_table("walk_events")
    op.drop_index(op.f("ix_photos_walk_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index("ix_gps_points_walk_id_timestamp", table_name="gps_points")
    op.drop_table("gps_points")
    op.drop_index("ix_walks_user_id_started_at", table_name="walks")
    op.drop_index(op.f("ix_walks_dog_id"), table_name="walks")
    op.drop_table("walks")
    op.drop_index(op.f("ix_testimonials_user_id"), table_name="testimonials")
    op.drop_table("testimonials")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_dogs_user_id"), table_name="dogs")
    op.drop_table("dogs")
    op.drop_table("users")
    # ### end Alembic commands ###
